name: Account Merge

on:
  issue_comment:
    types: [ created ]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Restore serverlist
        uses: actions/cache/restore@v4
        with:
          path: servers.bin
          key: ${{ runner.os }}-servers-
          restore-keys: ${{ runner.os }}-servers-

      - name: Save comment to file
        run: printf ${{ toJson(github.event.comment.body) }} > comment.txt

      - name: Download manifest
        run: dotnet run --configuration Release -- account -a comment.txt -t ${{ secrets.GITHUB_TOKEN }}

      - name: Save serverlist
        uses: actions/cache/save@v4
        with:
          path: servers.bin
          key: ${{ runner.os }}-servers-${{ hashFiles('servers.bin') }}
